PROJECT_TYPES = {

    "Noise Management": {
        "recommended_buffers": [50, 100, 200],
        "relevant_themes": ["Sensitive Receptors", "Planning / Local Government"],
        "layer_weights": {
            "residential": 4, "schools": 4, "hospitals": 4,
            "community_facilities": 3, "roads": 1,
            "esa": 0, "wetlands": 0, "native_vegetation": 0,
            "vegetation_complexes": 0, "ass": 0, "ass_estuaries": 0,
            "soil_landscape": 0, "soil_landscape_best": 0, "soil_group": 2, "groundwater_areas": 0,
            "groundwater_salinity": 0, "bores": 0,
            "contaminated_sites": 1, "local_government": 1,
            "aboriginal_heritage": 2, "historic_heritage": 2,
            "cadastre": 2, "residential_osm": 3,
        },
        "interpretation_rules": {
            "residential": {
                "Site": ("HIGH", "Residential receptors at site boundary — noise management plan required under EPA Guidance Statement No. 8"),
                "b1": ("HIGH", "Residential receptors within {b1}m — noise assessment required, acoustic report likely needed"),
                "b2": ("MEDIUM", "Residential receptors within {b2}m — preliminary noise screening recommended"),
                "b3": ("LOW", "Residential receptors within {b3}m — noted for preliminary screening"),
                "None": ("NONE", "No residential receptors within screening area"),
            },
            "schools": {
                "Site": ("HIGH", "School at site boundary — highly sensitive receptor, operational hours restriction required"),
                "b1": ("HIGH", "School within {b1}m — sensitive receptor, construction noise must comply with AS 2436"),
                "b2": ("HIGH", "School within {b2}m — sensitive receptor, noise assessment recommended"),
                "b3": ("MEDIUM", "School within {b3}m — sensitive receptor noted for screening"),
                "None": ("NONE", "No schools within screening area"),
            },
            "hospitals": {
                "Site": ("HIGH", "Hospital at site boundary — critical sensitive receptor, strict noise limits apply 24/7"),
                "b1": ("HIGH", "Hospital within {b1}m — critical receptor, night-time noise limits likely apply"),
                "b2": ("HIGH", "Hospital within {b2}m — sensitive receptor, noise management required"),
                "b3": ("MEDIUM", "Hospital within {b3}m — sensitive receptor noted"),
                "None": ("NONE", "No hospitals within screening area"),
            },
            "community_facilities": {
                "Site": ("HIGH", "Community facility at site boundary — sensitive receptor for noise"),
                "b1": ("MEDIUM", "Community facility within {b1}m — sensitive receptor, operational hours relevant"),
                "b2": ("LOW", "Community facility within {b2}m — noted for screening"),
                "b3": ("LOW", "Community facility within {b3}m — noted for screening"),
                "None": ("NONE", "No community facilities within screening area"),
            },
            "aboriginal_heritage": {
                "Site": ("MEDIUM", "Aboriginal heritage place at site — heritage consultation recommended regardless of project type"),
                "b1": ("MEDIUM", "Aboriginal heritage within {b1}m — heritage consultation recommended"),
                "b2": ("LOW", "Aboriginal heritage within {b2}m — noted for screening"),
                "b3": ("LOW", "Aboriginal heritage within {b3}m — noted for screening"),
                "None": ("NONE", "No Aboriginal heritage within screening area"),
            },
        },
        "not_relevant_layers": ["esa", "wetlands", "native_vegetation", "vegetation_complexes", "ass", "ass_estuaries", "soil_landscape", "soil_landscape_best", "groundwater_areas", "groundwater_salinity", "bores"],
    },

    "Dust Management": {
        "recommended_buffers": [50, 100, 200],
        "relevant_themes": ["Sensitive Receptors", "Ecology", "Planning / Local Government"],
        "layer_weights": {
            "residential": 4, "schools": 4, "hospitals": 4,
            "community_facilities": 3, "roads": 2,
            "esa": 2, "wetlands": 2, "native_vegetation": 2,
            "vegetation_complexes": 1, "ass": 0, "ass_estuaries": 0,
            "soil_landscape": 2, "soil_landscape_best": 2, "soil_group": 3, "groundwater_areas": 0,
            "groundwater_salinity": 0, "bores": 0,
            "contaminated_sites": 1, "local_government": 1,
            "aboriginal_heritage": 2, "historic_heritage": 2,
            "cadastre": 2, "residential_osm": 3,
        },
        "interpretation_rules": {
            "residential": {
                "Site": ("HIGH", "Residential receptors at site boundary — dust management plan required, health risk assessment likely needed"),
                "b1": ("HIGH", "Residential receptors within {b1}m — dust suppression measures mandatory during works"),
                "b2": ("MEDIUM", "Residential receptors within {b2}m — dust monitoring recommended during construction"),
                "b3": ("LOW", "Residential receptors within {b3}m — noted for preliminary dust screening"),
                "None": ("NONE", "No residential receptors within screening area"),
            },
            "schools": {
                "Site": ("HIGH", "School at site boundary — highly sensitive receptor for dust, health assessment required"),
                "b1": ("HIGH", "School within {b1}m — works may require school notification and dust monitoring"),
                "b2": ("MEDIUM", "School within {b2}m — dust management measures recommended"),
                "b3": ("LOW", "School within {b3}m — noted for screening"),
                "None": ("NONE", "No schools within screening area"),
            },
            "hospitals": {
                "Site": ("HIGH", "Hospital at site boundary — critical receptor for dust and air quality impacts"),
                "b1": ("HIGH", "Hospital within {b1}m — dust suppression mandatory, air quality monitoring recommended"),
                "b2": ("HIGH", "Hospital within {b2}m — dust management required"),
                "b3": ("MEDIUM", "Hospital within {b3}m — sensitive receptor noted"),
                "None": ("NONE", "No hospitals within screening area"),
            },
            "wetlands": {
                "Site": ("HIGH", "Wetland at site boundary — dust deposition may impact wetland ecological values"),
                "b1": ("MEDIUM", "Wetland within {b1}m — dust suppression required to protect wetland values"),
                "b2": ("LOW", "Wetland within {b2}m — dust deposition risk noted"),
                "b3": ("LOW", "Wetland within {b3}m — noted for screening"),
                "None": ("NONE", "No wetlands within screening area"),
            },
            "esa": {
                "Site": ("HIGH", "ESA at site boundary — dust deposition may impact sensitive ecological values"),
                "b1": ("MEDIUM", "ESA within {b1}m — dust management measures required to protect ecological values"),
                "b2": ("LOW", "ESA within {b2}m — dust risk noted"),
                "b3": ("LOW", "ESA within {b3}m — noted for screening"),
                "None": ("NONE", "No ESA within screening area"),
            },
            "soil_landscape": {
                "Site": ("MEDIUM", "Site intersects soil landscape unit — soil type relevant for dust generation potential"),
                "b1": ("LOW", "Soil landscape within {b1}m — soil characteristics may influence dust risk"),
                "b2": ("LOW", "Soil landscape within {b2}m — noted for screening"),
                "b3": ("LOW", "Soil landscape within {b3}m — noted for screening"),
                "None": ("NONE", "No soil landscape data within screening area"),
            },
        },
        "not_relevant_layers": ["ass", "ass_estuaries", "groundwater_areas", "groundwater_salinity", "bores"],
    },

    "Clearing / Vegetation Removal": {
        "recommended_buffers": [100, 250, 500],
        "relevant_themes": ["Ecology", "Heritage", "Planning / Local Government", "Groundwater / Hydrology"],
        "layer_weights": {
            "esa": 4, "wetlands": 4, "native_vegetation": 4,
            "vegetation_complexes": 3, "ass": 2, "ass_estuaries": 2,
            "soil_landscape": 2, "soil_landscape_best": 2, "soil_group": 2, "groundwater_areas": 3,
            "groundwater_salinity": 1, "bores": 1,
            "aboriginal_heritage": 3, "historic_heritage": 2,
            "contaminated_sites": 0, "local_government": 2,
            "residential": 0, "schools": 0, "hospitals": 0,
            "community_facilities": 0, "roads": 1, "cadastre": 0,
        },
        "interpretation_rules": {
            "esa": {
                "Site": ("HIGH", "ESA intersects site — clearing likely requires DWER approval under Environmental Protection Act 1986. Bush Forever and TEC areas may be prohibited from clearing"),
                "b1": ("HIGH", "ESA within {b1}m — clearing near ESA requires assessment, buffer from ESA boundary may be required"),
                "b2": ("MEDIUM", "ESA within {b2}m — clearing proposal should consider proximity to ESA"),
                "b3": ("LOW", "ESA within {b3}m — noted for preliminary screening"),
                "None": ("NONE", "No ESA identified within screening area"),
            },
            "wetlands": {
                "Site": ("HIGH", "Wetland intersects site — clearing near wetlands restricted under State Environmental Policy (SCP Wetlands) 2003"),
                "b1": ("HIGH", "Wetland within {b1}m — 50m vegetation buffer from wetland likely required"),
                "b2": ("MEDIUM", "Wetland within {b2}m — clearing proposal should address wetland buffer requirements"),
                "b3": ("LOW", "Wetland within {b3}m — noted for preliminary screening"),
                "None": ("NONE", "No wetlands identified within screening area"),
            },
            "native_vegetation": {
                "Site": ("HIGH", "Native vegetation present at site — clearing permit required if >1 ha or in a sensitive area"),
                "b1": ("MEDIUM", "Native vegetation within {b1}m — assess extent and condition before clearing"),
                "b2": ("LOW", "Native vegetation within {b2}m — noted for screening"),
                "b3": ("LOW", "Native vegetation within {b3}m — noted for screening"),
                "None": ("NONE", "No native vegetation mapped within screening area"),
            },
            "vegetation_complexes": {
                "Site": ("HIGH", "Vegetation complex present at site — TEC status should be confirmed before clearing"),
                "b1": ("MEDIUM", "Vegetation complex within {b1}m — complex type and conservation status should be assessed"),
                "b2": ("LOW", "Vegetation complex within {b2}m — noted for screening"),
                "b3": ("LOW", "Vegetation complex within {b3}m — noted for screening"),
                "None": ("NONE", "No vegetation complexes within screening area"),
            },
            "aboriginal_heritage": {
                "Site": ("HIGH", "Aboriginal heritage place at site — Section 18 consent under Aboriginal Heritage Act 1972 required before any ground disturbance"),
                "b1": ("HIGH", "Aboriginal heritage within {b1}m — heritage survey recommended prior to clearing"),
                "b2": ("MEDIUM", "Aboriginal heritage within {b2}m — heritage assessment recommended"),
                "b3": ("LOW", "Aboriginal heritage within {b3}m — noted for screening"),
                "None": ("NONE", "No Aboriginal heritage within screening area"),
            },
            "groundwater_areas": {
                "Site": ("MEDIUM", "Site within proclaimed groundwater area — clearing may affect groundwater recharge, DWER consultation recommended"),
                "b1": ("LOW", "Groundwater area within {b1}m — potential recharge impact noted"),
                "b2": ("LOW", "Groundwater area within {b2}m — noted for screening"),
                "b3": ("LOW", "Groundwater area within {b3}m — noted for screening"),
                "None": ("NONE", "No proclaimed groundwater areas within screening area"),
            },
        },
        "not_relevant_layers": ["contaminated_sites", "residential", "schools", "hospitals", "community_facilities", "cadastre"],
    },

    "Contamination Assessment": {
        "recommended_buffers": [100, 250, 500],
        "relevant_themes": ["Contaminated Land", "ASS / Soils / Geology", "Groundwater / Hydrology", "Planning / Local Government"],
        "layer_weights": {
            "contaminated_sites": 4, "ass": 4, "ass_estuaries": 4,
            "soil_landscape": 3, "soil_landscape_best": 3, "soil_group": 3, "groundwater_areas": 3,
            "groundwater_salinity": 3, "bores": 2,
            "wetlands": 2, "esa": 1,
            "aboriginal_heritage": 2, "historic_heritage": 1,
            "local_government": 1, "residential": 2,
            "schools": 2, "hospitals": 2,
            "community_facilities": 1, "roads": 0,
            "native_vegetation": 0, "vegetation_complexes": 0,
            "cadastre": 1,
        },
        "interpretation_rules": {
            "contaminated_sites": {
                "Site": ("HIGH", "Contaminated site intersects or overlaps proposed site — Phase 1 Environmental Site Assessment mandatory before any development"),
                "b1": ("HIGH", "Contaminated site within {b1}m — Phase 1 ESA recommended, potential for contamination migration to site"),
                "b2": ("MEDIUM", "Contaminated site within {b2}m — contamination migration pathway should be assessed"),
                "b3": ("LOW", "Contaminated site within {b3}m — noted for preliminary screening"),
                "None": ("LOW", "No classified contaminated sites within screening area — note: absence does not confirm clean site, historical land use assessment still recommended"),
            },
            "ass": {
                "Site": ("HIGH", "Acid Sulfate Soils risk mapped at site — ASS investigation required before any earthworks, dewatering or drainage works"),
                "b1": ("HIGH", "ASS risk within {b1}m — ASS management plan likely required for any ground disturbance"),
                "b2": ("MEDIUM", "ASS risk within {b2}m — ASS investigation recommended"),
                "b3": ("LOW", "ASS risk within {b3}m — noted for preliminary screening"),
                "None": ("NONE", "No ASS risk mapping within screening area"),
            },
            "groundwater_areas": {
                "Site": ("HIGH", "Site within proclaimed groundwater area — contamination may affect groundwater resources, DWER notification may be required"),
                "b1": ("HIGH", "Groundwater area within {b1}m — groundwater contamination pathway assessment required"),
                "b2": ("MEDIUM", "Groundwater area within {b2}m — groundwater sensitivity noted"),
                "b3": ("LOW", "Groundwater area within {b3}m — noted for screening"),
                "None": ("NONE", "No proclaimed groundwater areas within screening area"),
            },
            "groundwater_salinity": {
                "Site": ("MEDIUM", "Groundwater salinity data available at site — salinity classification relevant for contamination risk assessment"),
                "b1": ("LOW", "Groundwater salinity data within {b1}m — noted for screening"),
                "b2": ("LOW", "Groundwater salinity data within {b2}m — noted for screening"),
                "b3": ("LOW", "Groundwater salinity data within {b3}m — noted for screening"),
                "None": ("NONE", "No groundwater salinity data within screening area"),
            },
            "soil_landscape": {
                "Site": ("MEDIUM", "Soil landscape data available — soil type relevant for contaminant mobility and remediation planning"),
                "b1": ("LOW", "Soil landscape within {b1}m — soil characteristics noted"),
                "b2": ("LOW", "Soil landscape within {b2}m — noted for screening"),
                "b3": ("LOW", "Soil landscape within {b3}m — noted for screening"),
                "None": ("NONE", "No soil landscape data within screening area"),
            },
            "soil_landscape_best": {
                "Site": ("MEDIUM", "Soil landscape data available — soil type relevant for contaminant mobility and remediation planning"),
                "b1": ("LOW", "Soil landscape within {b1}m — soil characteristics noted"),
                "b2": ("LOW", "Soil landscape within {b2}m — noted for screening"),
                "b3": ("LOW", "Soil landscape within {b3}m — noted for screening"),
                "None": ("NONE", "No soil landscape data within screening area"),
            },
        },
        "not_relevant_layers": ["native_vegetation", "vegetation_complexes", "roads", "community_facilities"],
    },

    "Groundwater Impact": {
        "recommended_buffers": [100, 250, 500],
        "relevant_themes": ["Groundwater / Hydrology", "Ecology", "Contaminated Land", "ASS / Soils / Geology"],
        "layer_weights": {
            "groundwater_areas": 4, "groundwater_salinity": 3,
            "bores": 3, "wetlands": 4, "esa": 3,
            "ass": 3, "ass_estuaries": 3, "soil_landscape": 2, "soil_landscape_best": 2, "soil_group": 2,
            "native_vegetation": 2, "vegetation_complexes": 2,
            "contaminated_sites": 3, "local_government": 1,
            "aboriginal_heritage": 2, "historic_heritage": 1,
            "residential": 1, "schools": 1, "hospitals": 1,
            "community_facilities": 0, "roads": 0, "cadastre": 0,
        },
        "interpretation_rules": {
            "groundwater_areas": {
                "Site": ("HIGH", "Site within proclaimed groundwater area — groundwater licence may be required, DWER consultation mandatory"),
                "b1": ("HIGH", "Proclaimed groundwater area within {b1}m — groundwater impact assessment required"),
                "b2": ("MEDIUM", "Proclaimed groundwater area within {b2}m — groundwater sensitivity noted, assessment recommended"),
                "b3": ("LOW", "Proclaimed groundwater area within {b3}m — noted for preliminary screening"),
                "None": ("LOW", "No proclaimed groundwater areas within screening area — note: unproclaimed areas may still require assessment"),
            },
            "wetlands": {
                "Site": ("HIGH", "Wetland at site — groundwater-dependent ecosystem likely present, impacts to groundwater levels may affect wetland values"),
                "b1": ("HIGH", "Wetland within {b1}m — groundwater drawdown modelling recommended to assess wetland impacts"),
                "b2": ("MEDIUM", "Wetland within {b2}m — potential groundwater dependency should be assessed"),
                "b3": ("LOW", "Wetland within {b3}m — noted for preliminary screening"),
                "None": ("NONE", "No wetlands within screening area"),
            },
            "bores": {
                "Site": ("HIGH", "Monitoring bores at site — existing groundwater data available, baseline conditions should be established"),
                "b1": ("MEDIUM", "Monitoring bores within {b1}m — existing groundwater data may be available for baseline assessment"),
                "b2": ("LOW", "Monitoring bores within {b2}m — noted for screening"),
                "b3": ("LOW", "Monitoring bores within {b3}m — noted for screening"),
                "None": ("LOW", "No monitoring bores within screening area — installation of monitoring bores may be required"),
            },
            "ass": {
                "Site": ("HIGH", "ASS risk at site — dewatering or groundwater drawdown may mobilise acid sulfate soils, ASS management plan required"),
                "b1": ("HIGH", "ASS risk within {b1}m — groundwater works must consider ASS mobilisation risk"),
                "b2": ("MEDIUM", "ASS risk within {b2}m — ASS risk noted in context of groundwater works"),
                "b3": ("LOW", "ASS risk within {b3}m — noted for screening"),
                "None": ("NONE", "No ASS risk within screening area"),
            },
            "contaminated_sites": {
                "Site": ("HIGH", "Contaminated site at location — groundwater contamination plume likely present, groundwater investigation required"),
                "b1": ("HIGH", "Contaminated site within {b1}m — groundwater contamination migration pathway assessment required"),
                "b2": ("MEDIUM", "Contaminated site within {b2}m — contamination pathway noted"),
                "b3": ("LOW", "Contaminated site within {b3}m — noted for screening"),
                "None": ("NONE", "No classified contaminated sites within screening area"),
            },
            "soil_landscape_best": {
                "Site": ("MEDIUM", "Soil landscape data available — soil type relevant for contaminant mobility and remediation planning"),
                "b1": ("LOW", "Soil landscape within {b1}m — soil characteristics noted"),
                "b2": ("LOW", "Soil landscape within {b2}m — noted for screening"),
                "b3": ("LOW", "Soil landscape within {b3}m — noted for screening"),
                "None": ("NONE", "No soil landscape data within screening area"),
            },
        },
        "not_relevant_layers": ["roads", "community_facilities", "cadastre", "historic_heritage"],
    },

    "Heritage Assessment": {
        "recommended_buffers": [100, 250, 500],
        "relevant_themes": ["Heritage", "Ecology", "Planning / Local Government"],
        "layer_weights": {
            "aboriginal_heritage": 4, "historic_heritage": 4,
            "esa": 2, "wetlands": 2, "native_vegetation": 2,
            "vegetation_complexes": 2, "local_government": 2,
            "contaminated_sites": 0, "ass": 0, "ass_estuaries": 0,
            "soil_landscape": 1, "soil_landscape_best": 1, "soil_group": 2, "groundwater_areas": 0,
            "groundwater_salinity": 0, "bores": 0,
            "residential": 0, "schools": 0, "hospitals": 0,
            "community_facilities": 1, "roads": 0, "cadastre": 0,
        },
        "interpretation_rules": {
            "aboriginal_heritage": {
                "Site": ("HIGH", "Registered Aboriginal heritage place intersects site — Section 18 consent under Aboriginal Heritage Act 1972 required before any ground disturbance"),
                "b1": ("HIGH", "Aboriginal heritage within {b1}m — heritage survey recommended, potential for unregistered places within site"),
                "b2": ("MEDIUM", "Aboriginal heritage within {b2}m — heritage assessment recommended prior to development"),
                "b3": ("LOW", "Aboriginal heritage within {b3}m — noted for preliminary screening"),
                "None": ("LOW", "No registered Aboriginal heritage within screening area — note: unregistered sites may be present, heritage survey recommended for ground-disturbing works"),
            },
            "historic_heritage": {
                "Site": ("HIGH", "State Heritage Register place at site — development may require Heritage Council of WA approval"),
                "b1": ("HIGH", "State Heritage Register place within {b1}m — development within proximity may require heritage impact assessment"),
                "b2": ("MEDIUM", "State Heritage Register place within {b2}m — heritage setting and views should be considered"),
                "b3": ("LOW", "State Heritage Register place within {b3}m — noted for preliminary screening"),
                "None": ("LOW", "No State Heritage Register places within screening area — local heritage inventory should also be checked"),
            },
            "esa": {
                "Site": ("MEDIUM", "ESA at site — ecological values may be associated with cultural heritage landscape"),
                "b1": ("LOW", "ESA within {b1}m — ecological and cultural heritage values may be interconnected"),
                "b2": ("LOW", "ESA within {b2}m — noted for screening"),
                "b3": ("LOW", "ESA within {b3}m — noted for screening"),
                "None": ("NONE", "No ESA within screening area"),
            },
            "wetlands": {
                "Site": ("MEDIUM", "Wetland at site — wetlands may have cultural significance to Aboriginal communities"),
                "b1": ("LOW", "Wetland within {b1}m — cultural significance should be considered in heritage assessment"),
                "b2": ("LOW", "Wetland within {b2}m — noted for screening"),
                "b3": ("LOW", "Wetland within {b3}m — noted for screening"),
                "None": ("NONE", "No wetlands within screening area"),
            },
        },
        "not_relevant_layers": ["contaminated_sites", "ass", "ass_estuaries", "groundwater_areas", "groundwater_salinity", "bores", "residential", "schools", "hospitals", "roads", "cadastre"],
    },

    "General Environmental Assessment": {
        "recommended_buffers": [100, 250, 500],
        "relevant_themes": ["Ecology", "ASS / Soils / Geology", "Heritage", "Groundwater / Hydrology", "Contaminated Land", "Sensitive Receptors", "Planning / Local Government"],
        "layer_weights": {
            "esa": 4, "wetlands": 4, "native_vegetation": 3,
            "vegetation_complexes": 3, "ass": 3, "ass_estuaries": 3,
            "soil_landscape": 2, "soil_landscape_best": 2, "soil_group": 2, "groundwater_areas": 3,
            "groundwater_salinity": 2, "bores": 2,
            "aboriginal_heritage": 4, "historic_heritage": 3,
            "contaminated_sites": 4, "local_government": 2,
            "residential": 2, "schools": 2, "hospitals": 2,
            "community_facilities": 2, "roads": 1,
            "cadastre": 1, "residential_osm": 2,
        },
        "interpretation_rules": {},
        "not_relevant_layers": [],
    },

    "Custom": {
        "recommended_buffers": [100, 250, 500],
        "relevant_themes": ["Ecology", "ASS / Soils / Geology", "Heritage", "Groundwater / Hydrology", "Contaminated Land", "Sensitive Receptors", "Planning / Local Government"],
        "layer_weights": {
            "esa": 3, "wetlands": 3, "native_vegetation": 2,
            "vegetation_complexes": 2, "ass": 3, "ass_estuaries": 3,
            "soil_landscape": 2, "soil_landscape_best": 2, "soil_group": 2, "groundwater_areas": 2,
            "groundwater_salinity": 2, "bores": 2,
            "aboriginal_heritage": 3, "historic_heritage": 3,
            "contaminated_sites": 3, "local_government": 2,
            "residential": 2, "schools": 2, "hospitals": 2,
            "community_facilities": 2, "roads": 1,
            "cadastre": 1, "residential_osm": 2,
        },
        "interpretation_rules": {},
        "not_relevant_layers": [],
    },
}

GENERIC_INTERPRETATIONS = {
    "Site": "Feature intersects the site directly — further investigation recommended",
    "b1": "Feature identified within the inner buffer zone — assessment recommended",
    "b2": "Feature identified within the middle buffer zone — noted for screening",
    "b3": "Feature identified within the outer buffer zone — noted for preliminary review",
    "None": "No features identified within the screening area",
}

GENERIC_RISK_BY_TRIGGER = {
    "Site": "HIGH",
    "b1": "MEDIUM",
    "b2": "LOW",
    "b3": "LOW",
    "None": "NONE",
}